name: Gatsby Publish

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: export NODE_OPTIONS=--openssl-legacy-provider
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{secrets.portfolio}}
          deploy-branch: deploy
          gatsby-args: --prefix-paths
